# Generated by Django 5.0.4 on 2024-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="course",
        ),
        migrations.AddField(
            model_name="staff",
            name="course",
            field=models.ManyToManyField(to="main_app.course"),
        ),
    ]
