# Generated by Django 5.0.4 on 2024-04-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_remove_staff_course_staff_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackstaff",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.course",
            ),
        ),
    ]
