# Generated by Django 5.0.4 on 2024-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_feedbackstaff_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="session",
        ),
        migrations.AddField(
            model_name="student",
            name="session",
            field=models.ManyToManyField(to="main_app.session"),
        ),
    ]
